CREATE USER hr IDENTIFIED BY hr;

GRANT CONNECT, RESOURCE TO hr;

ALTER USER hr QUOTA UNLIMITED ON USERS;

GRANT CREATE VIEW TO hr;
GRANT CREATE SYNONYM TO hr;
GRANT CREATE SEQUENCE TO hr;
GRANT CREATE PROCEDURE TO hr;
GRANT CREATE TRIGGER TO hr;
GRANT CREATE TYPE TO hr;